source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'

pod 'HYPNorwegianAccountNumber'
pod 'NSDictionary-ANDYSafeValue'
pod 'NSJSONSerialization-ANDYJSONFile'
pod 'NSString-ZENInflections'
pod 'UIScreen-HYPLiveBounds'
pod 'UIButton-ANDYHighlighted'

pod 'HYPImagePicker', :git => 'https://github.com/hyperoslo/HYPImagePicker.git'
pod 'HYPNorwegianSSN', :git => 'https://github.com/hyperoslo/HYPNorwegianSSN.git'
pod 'NSString-HYPFormula', :git => 'https://github.com/hyperoslo/NSString-HYPFormula.git'
pod 'NSString-HYPWordExtractor', :git => 'https://github.com/hyperoslo/NSString-HYPWordExtractor.git'
pod 'UIColor-ANDYHex', :git => 'https://github.com/NSElvis/UIColor-ANDYHex.git'
pod 'NSString-HYPContainsString', :git => 'https://github.com/hyperoslo/NSString-HYPContainsString.git'
pod 'DDMathParser', :git => 'https://github.com/hyperoslo/DDMathParser.git'
pod 'NSObject-HYPTesting', :git => 'https://github.com/hyperoslo/NSObject-HYPTesting.git'
