source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'
link_with 'HYPForms', 'HYPFormsTests'

pod 'UIScreen-HYPLiveBounds'
pod 'NSString-ZENInflections'
pod 'UIColor-ANDYHex', :git => 'https://github.com/NSElvis/UIColor-ANDYHex.git'
pod 'NSDictionary-HYPSafeValue', :git => 'https://github.com/hyperoslo/NSDictionary-HYPSafeValue.git'
pod 'HYPNorwegianSSN', :git => 'https://github.com/hyperoslo/HYPNorwegianSSN.git'
pod 'NSString-HYPWordExtractor', :git => 'https://github.com/hyperoslo/NSString-HYPWordExtractor.git'
pod 'NSString-HYPFormula', :git => 'https://github.com/hyperoslo/NSString-HYPFormula.git'
pod 'HYPImagePicker', :git => 'https://github.com/hyperoslo/HYPImagePicker.git'
pod 'NSJSONSerialization-ANDYJSONFile'
